pipeline {
  agent any

  stages {
    stage('Back-end') {
      steps {
        bat 'docker run maven:3.8.1-adoptopenjdk-11 mvn --version'
      }
    }
    stage('Front-end') {
      steps {
        bat 'docker run node:16-alpine node --version'
      }
    }
  }
}
